FROM rust:bullseye

RUN set -xe && \
  apt-get update && \
  apt-get install -y --no-install-recommends locales && \
  rm -rf /var/lib/apt/lists/* && \
  echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
  locale-gen
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

RUN set -xe && \
  apt-get update && \
  apt-get install -y --no-install-recommends libseccomp-dev && \
  rm -rf /var/lib/apt/lists/*

RUN set -xe && \
  apt-get update && \
  apt-get install -y --no-install-recommends bc && \
  apt-get install -y --no-install-recommends iputils-ping && \
  rm -rf /var/lib/apt/lists/*

RUN groupadd --gid 1000 hako \
  && useradd --uid 1000 --gid hako --shell /bin/bash --create-home hako

USER 1000:1000
WORKDIR /home/hako/app

RUN cargo new --lib ./hakoniwa
RUN cargo new ./hakoniwa-cli
COPY --chown=1000:1000 ./hakoniwa/Cargo.toml ./hakoniwa
COPY --chown=1000:1000 ./hakoniwa-cli/Cargo.toml ./hakoniwa-cli
COPY --chown=1000:1000 ./Cargo.toml .
COPY --chown=1000:1000 ./Cargo.lock .
RUN cargo build && rm -rf ./target/debug/*/*hakoniwa*
RUN cargo build --release && rm -rf ./target/release/*/*hakoniwa*

COPY --chown=1000:1000 . .
