FROM hakoniwa-devcontainer:latest

RUN cargo build --release

USER root
RUN mv ./target/release/hakoniwa /bin/hakoniwa
RUN cd /home/hako && ls -A1 | xargs rm -rf {}

USER 1000:1000
WORKDIR /home/hako
