name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  dist:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Install libseccomp
        run: |
          sudo apt-get update
          sudo apt install libseccomp-dev
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo build
        run: |
          cargo build --target x86_64-unknown-linux-gnu --release --locked
          mkdir dist && mv target/x86_64-unknown-linux-gnu/release/hakoniwa dist
          tar -czvf hakoniwa-x86_64-unknown-linux-gnu.tar.gz -C dist .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-x86_64-unknown-linux-gnu
          path: hakoniwa-x86_64-unknown-linux-gnu.tar.gz

  dist-musl:
    name: Build - Musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Install musl libc
        run: |
          sudo apt-get update
          sudo apt-get install musl-tools
      - name: Install libseccomp
        uses: ./.github/actions/setup
        with:
          version: main
          link-type: static
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-musl
      - name: Run cargo build
        run: |
          cargo build --target x86_64-unknown-linux-musl --release --locked
          mkdir dist && mv target/x86_64-unknown-linux-musl/release/hakoniwa dist
          tar -czvf hakoniwa-x86_64-unknown-linux-musl.tar.gz -C dist .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-x86_64-unknown-linux-musl
          path: hakoniwa-x86_64-unknown-linux-musl.tar.gz

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - dist
      - dist-musl
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist-x86_64-unknown-linux-gnu
          path: dist
      - uses: actions/download-artifact@v4
        with:
          name: dist-x86_64-unknown-linux-musl
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
          draft: true
